[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket-server/:splat"
  status = 200
  force = true
  conditions = { Role = ["admin", "user"] }

[functions]
  directory = "netlify/functions"
